### ISSUE TITLE
Azion CLI

### ISSUE THREAD

**Issue by robsongajunior** [lsferreira42/azion#1]
Nice, good job man! I appreciate a lot.

`Azion Technologies` has a binary CLI launched in the end of last year! We appreciate your interesting and if you want you can use the CLI and report anything for us!

- First steps: https://www.azion.com/en/documentation/products/cli/first-steps/
- Edge Application: https://www.azion.com/en/documentation/products/cli/edge-applications/

**Comment by lsferreira42** [comment]
@robsongajunior Hello, thank you for the suggestion!
I already tried, but at that time it only supported edge functions, good to see it support edge applications now.

Any plans to support edge firewall and network lists?
This is basically the reason i am writing this, and of course to code a little bit more every day since i became a tech lead!

**Comment by gabrielAnFran** [comment]
Hey, man. Well done!

Azion has an SDK for Go that gives you a set of possibilities as well, in case you're interested: 

- SDK -> https://github.com/aziontech/azionapi-go-sdk
- SDK implementation -> https://github.com/gabrielAnFran/idns-using-azion-go-sdk

And, if you want to take a look at the CLI source code, since it's an open source project --> https://github.com/aziontech/azion-cli
